// Code generated by catalog-gen. DO NOT EDIT.
// To regenerate: catalog-gen generate
// Source: catalog.yaml

package service

import (
	"github.com/kubeflow/model-registry/internal/db/filter"

	"github.com/kubeflow/model-registry/catalog/plugins/mcp/internal/db/models"
)

func init() {
	// Register McpServer entity properties in the global filter property map.
	// This allows filterQuery validation and property resolution for McpServer entities.
	filter.RestEntityPropertyMap[models.RestEntityMcpServer] = map[string]bool{
		// Built-in entity table properties
		"id": true, "name": true, "externalId": true,
		"createTimeSinceEpoch": true, "lastUpdateTimeSinceEpoch": true,
		"serverUrl": true,
		"transportType": true,
		"toolCount": true,
		"resourceCount": true,
		"promptCount": true,
	}
}

// entityMappings implements filter.EntityMappingFunctions for McpServer entities.
type entityMappings struct{}

// GetMLMDEntityType maps a REST entity type to its underlying MLMD entity type.
// McpServer entities are stored as MLMD Contexts.
func (m *entityMappings) GetMLMDEntityType(t filter.RestEntityType) filter.EntityType {
	return filter.EntityTypeContext
}

// GetPropertyDefinitionForRestEntity returns the property definition for a REST entity property.
// It maps well-known properties to their storage locations and types.
func (m *entityMappings) GetPropertyDefinitionForRestEntity(t filter.RestEntityType, prop string) filter.PropertyDefinition {
	switch prop {
	// Entity table columns (Context table)
	case "id":
		return filter.PropertyDefinition{Location: filter.EntityTable, ValueType: "int_value", Column: "id"}
	case "name":
		return filter.PropertyDefinition{Location: filter.EntityTable, ValueType: "string_value", Column: "name"}
	case "externalId":
		return filter.PropertyDefinition{Location: filter.EntityTable, ValueType: "string_value", Column: "external_id"}
	case "createTimeSinceEpoch":
		return filter.PropertyDefinition{Location: filter.EntityTable, ValueType: "int_value", Column: "create_time_since_epoch"}
	case "lastUpdateTimeSinceEpoch":
		return filter.PropertyDefinition{Location: filter.EntityTable, ValueType: "int_value", Column: "last_update_time_since_epoch"}
	case "serverUrl":
		return filter.PropertyDefinition{Location: filter.PropertyTable, ValueType: "string_value", Column: "serverUrl"}
	case "transportType":
		return filter.PropertyDefinition{Location: filter.PropertyTable, ValueType: "string_value", Column: "transportType"}
	case "toolCount":
		return filter.PropertyDefinition{Location: filter.PropertyTable, ValueType: "int_value", Column: "toolCount"}
	case "resourceCount":
		return filter.PropertyDefinition{Location: filter.PropertyTable, ValueType: "int_value", Column: "resourceCount"}
	case "promptCount":
		return filter.PropertyDefinition{Location: filter.PropertyTable, ValueType: "int_value", Column: "promptCount"}

	default:
		// Unknown properties are treated as custom properties in the ContextProperty table
		return filter.PropertyDefinition{
			Location:  filter.Custom,
			ValueType: "string_value",
			Column:    prop,
		}
	}
}

// IsChildEntity returns true if the REST entity type uses prefixed names (parentId:name).
// Catalog entities are top-level and do not use prefixed names.
func (m *entityMappings) IsChildEntity(t filter.RestEntityType) bool {
	return false
}
