// Code generated by catalog-gen. DO NOT EDIT.
// To regenerate: catalog-gen generate
// Source: catalog.yaml

package service

import (
	"github.com/kubeflow/model-registry/catalog/plugins/mcp/internal/db/models"
	"github.com/kubeflow/model-registry/internal/datastore"
)

const (
	McpServerTypeName = "kf.McpServer"
)

// DatastoreSpec returns the datastore specification for this catalog.
// This defines the types and properties that will be stored in the MLMD database.
func DatastoreSpec() *datastore.Spec {
	return datastore.NewSpec().
		AddContext(McpServerTypeName, datastore.NewSpecType(NewMcpServerRepository).
			AddString("source_id").
			AddString("serverUrl").
			AddString("transportType").
			AddInt("toolCount").
			AddInt("resourceCount").
			AddInt("promptCount"),
		)
}

// Services holds all repository instances for this catalog.
type Services struct {
	McpServerRepository models.McpServerRepository
}

// NewServices creates a new Services instance from repository instances.
func NewServices(
	mcpserverRepository models.McpServerRepository,
) Services {
	return Services{
		McpServerRepository: mcpserverRepository,
	}
}
