// Code generated by catalog-gen. DO NOT EDIT.
// To regenerate: catalog-gen generate
// Source: catalog.yaml

package models

import (
	"github.com/kubeflow/model-registry/internal/db/filter"
	"github.com/kubeflow/model-registry/internal/db/models"
)

// RestEntityMcpServer is the filter.RestEntityType constant for McpServer entities.
const RestEntityMcpServer filter.RestEntityType = "McpServer"

// McpServerAttributes contains the attributes for a McpServer entity.
type McpServerAttributes struct {
	Name                     *string
	ExternalID               *string
	CreateTimeSinceEpoch     *int64
	LastUpdateTimeSinceEpoch *int64
	ServerUrl	*string
	TransportType	*string
	ToolCount	*int32
	ResourceCount	*int32
	PromptCount	*int32
}

// McpServer is the interface for McpServer entities.
// It extends the shared Entity interface with McpServer-specific attributes.
type McpServer interface {
	models.Entity[McpServerAttributes]
}

// McpServerImpl is the concrete implementation of the McpServer interface.
// It uses the shared BaseEntity implementation.
type McpServerImpl = models.BaseEntity[McpServerAttributes]

// NewMcpServer creates a new McpServer entity.
func NewMcpServer(attrs *McpServerAttributes) McpServer {
	return &McpServerImpl{
		Attributes: attrs,
	}
}

// McpServerListOptions contains options for listing McpServer entities.
type McpServerListOptions struct {
	models.Pagination
	Name       *string
	ExternalID *string
	SourceIDs  *[]string
	Query      *string
}

// GetRestEntityType implements the FilterApplier interface for advanced filtering.
func (o *McpServerListOptions) GetRestEntityType() filter.RestEntityType {
	return RestEntityMcpServer
}

// McpServerRepository is the interface for McpServer data access.
type McpServerRepository interface {
	GetByID(id int32) (McpServer, error)
	GetByName(name string) (McpServer, error)
	List(options McpServerListOptions) (*models.ListWrapper[McpServer], error)
	Save(entity McpServer) (McpServer, error)
	DeleteBySource(sourceID string) error
	DeleteByID(id int32) error
	GetDistinctSourceIDs() ([]string, error)
}
